/* Generated by ncc from lex.n */
#include "nyxrt.h"

static inline nyx_i64 write(nyx_i32 fd, nyx_u8* buf, nyx_isize len) {
    return (nyx_i64)__nyx_syscall6(1, (nyx_i64)fd, (nyx_i64)buf, (nyx_i64)len, 0, 0, 0);
}
static inline nyx_i64 sys_open(nyx_u8* path, nyx_i64 flags, nyx_i64 mode) {
    return (nyx_i64)__nyx_syscall6(3, (nyx_i64)path, (nyx_i64)flags, (nyx_i64)mode, 0, 0, 0);
}
static inline nyx_i64 sys_read(nyx_i64 fd, nyx_u8* buf, nyx_isize len) {
    return (nyx_i64)__nyx_syscall6(4, (nyx_i64)fd, (nyx_i64)buf, (nyx_i64)len, 0, 0, 0);
}
static inline nyx_i64 sys_close(nyx_i64 fd) {
    return (nyx_i64)__nyx_syscall6(5, (nyx_i64)fd, 0, 0, 0, 0, 0);
}
static inline nyx_i64 sys_sbrk(nyx_i64 incr) {
    return (nyx_i64)__nyx_syscall6(7, (nyx_i64)incr, 0, 0, 0, 0, 0);
}

void put(nyx_str s);
nyx_bool is_idc(nyx_i64 b);
nyx_bool is_dg(nyx_i64 b);
nyx_bool is_hx(nyx_i64 b);
nyx_i64 hxv(nyx_i64 d);
nyx_bool eq2(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b);
nyx_bool eq3(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c);
nyx_bool eq4(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d);
nyx_bool eq5(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e);
nyx_bool eq6(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f);
nyx_bool eq7(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g);
nyx_bool eq8(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g, nyx_i64 h);
nyx_i64 kwlook(nyx_u8* p, nyx_i64 s, nyx_i64 n);
nyx_i64 scan_string(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 cont);
nyx_i64 next_kind(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void dump_tok(nyx_u8* p, nyx_i64* st, nyx_i64 k);
nyx_i64 main(nyx_i64 __argc, nyx_u8** __argv);

void put(nyx_str s) {
    write(1, (nyx_u8*)(((nyx_u8*)s.ptr)), (nyx_isize)(s.len));
}

nyx_bool is_idc(nyx_i64 b) {
    return ((((b >= 97) && (b <= 122)) || ((b >= 65) && (b <= 90))) || (b == 95));
}

nyx_bool is_dg(nyx_i64 b) {
    return ((b >= 48) && (b <= 57));
}

nyx_bool is_hx(nyx_i64 b) {
    return ((is_dg(b) || ((b >= 97) && (b <= 102))) || ((b >= 65) && (b <= 70)));
}

nyx_i64 hxv(nyx_i64 d) {
    if (is_dg(d)) {
        return (d - 48);
    }
    if ((d >= 97)) {
        return (d - 87);
    }
    return (d - 55);
}

nyx_bool eq2(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b) {
    return (((nyx_i64)(p[s]) == a) && ((nyx_i64)(p[(s + 1)]) == b));
}

nyx_bool eq3(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c) {
    return (eq2(p, s, a, b) && ((nyx_i64)(p[(s + 2)]) == c));
}

nyx_bool eq4(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d) {
    return (eq3(p, s, a, b, c) && ((nyx_i64)(p[(s + 3)]) == d));
}

nyx_bool eq5(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e) {
    return (eq4(p, s, a, b, c, d) && ((nyx_i64)(p[(s + 4)]) == e));
}

nyx_bool eq6(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f) {
    return (eq5(p, s, a, b, c, d, e) && ((nyx_i64)(p[(s + 5)]) == f));
}

nyx_bool eq7(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g) {
    return (eq6(p, s, a, b, c, d, e, f) && ((nyx_i64)(p[(s + 6)]) == g));
}

nyx_bool eq8(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g, nyx_i64 h) {
    return (eq7(p, s, a, b, c, d, e, f, g) && ((nyx_i64)(p[(s + 7)]) == h));
}

nyx_i64 kwlook(nyx_u8* p, nyx_i64 s, nyx_i64 n) {
    if ((n == 2)) {
        if (eq2(p, s, 102, 110)) {
            return 10;
        }
        if (eq2(p, s, 97, 115)) {
            return 18;
        }
        if (eq2(p, s, 105, 102)) {
            return 13;
        }
        if (eq2(p, s, 105, 110)) {
            return 29;
        }
    }
    if ((n == 3)) {
        if (eq3(p, s, 109, 117, 116)) {
            return 11;
        }
        if (eq3(p, s, 114, 97, 119)) {
            return 19;
        }
        if (eq3(p, s, 102, 111, 114)) {
            return 28;
        }
        if (eq3(p, s, 111, 119, 110)) {
            return 36;
        }
    }
    if ((n == 4)) {
        if (eq4(p, s, 101, 108, 115, 101)) {
            return 14;
        }
        if (eq4(p, s, 116, 114, 117, 101)) {
            return 20;
        }
        if (eq4(p, s, 101, 110, 117, 109)) {
            return 24;
        }
        if (eq4(p, s, 105, 109, 112, 108)) {
            return 27;
        }
    }
    if ((n == 5)) {
        if (eq5(p, s, 119, 104, 105, 108, 101)) {
            return 15;
        }
        if (eq5(p, s, 98, 114, 101, 97, 107)) {
            return 16;
        }
        if (eq5(p, s, 102, 97, 108, 115, 101)) {
            return 21;
        }
        if (eq5(p, s, 100, 101, 102, 101, 114)) {
            return 23;
        }
        if (eq5(p, s, 109, 97, 116, 99, 104)) {
            return 25;
        }
    }
    if ((n == 6)) {
        if (eq6(p, s, 101, 120, 116, 101, 114, 110)) {
            return 8;
        }
        if (eq6(p, s, 115, 116, 114, 117, 99, 116)) {
            return 22;
        }
        if (eq6(p, s, 114, 101, 116, 117, 114, 110)) {
            return 12;
        }
    }
    if ((n == 7)) {
        if (eq7(p, s, 115, 121, 115, 99, 97, 108, 108)) {
            return 9;
        }
    }
    if ((n == 8)) {
        if (eq8(p, s, 99, 111, 110, 116, 105, 110, 117, 101)) {
            return 17;
        }
    }
    return 7;
}

nyx_i64 scan_string(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 cont) {
    st[5] = st[1];
    nyx_i64 cnt = 0;
    nyx_bool going = 1;
    while (going) {
        if ((st[0] >= n)) {
            return -(1);
        }
        nyx_i64 b = (nyx_i64)(p[st[0]]);
        if ((b == 34)) {
            st[0] = (st[0] + 1);
            st[6] = cnt;
            if ((cont == 1)) {
                return 5;
            }
            return 2;
        }
        if ((b == 123)) {
            st[0] = (st[0] + 1);
            if (((st[2] + 1) >= 16)) {
                return -(1);
            }
            st[2] = (st[2] + 1);
            st[(8 + st[2])] = st[3];
            st[6] = cnt;
            if ((cont == 1)) {
                return 4;
            }
            return 3;
        }
        if ((b == 92)) {
            st[0] = (st[0] + 1);
            if ((st[0] >= n)) {
                return -(1);
            }
            nyx_i64 e = (nyx_i64)(p[st[0]]);
            st[0] = (st[0] + 1);
            nyx_bool ok = (((((((((e == 110) || (e == 116)) || (e == 114)) || (e == 48)) || (e == 92)) || (e == 34)) || (e == 39)) || (e == 123)) || (e == 125));
            if (!(ok)) {
                return -(1);
            }
            cnt = (cnt + 1);
            continue;
        }
        if ((b == 10)) {
            st[1] = (st[1] + 1);
        }
        cnt = (cnt + 1);
        st[0] = (st[0] + 1);
    }
    return 0;
}

nyx_i64 next_kind(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    if ((st[4] == 1)) {
        st[4] = 0;
        return scan_string(p, n, st, 1);
    }
    nyx_i64 b = 0;
    nyx_bool scanning = 1;
    while (scanning) {
        if ((st[0] >= n)) {
            st[5] = st[1];
            return 0;
        }
        b = (nyx_i64)(p[st[0]]);
        if ((((b == 32) || (b == 9)) || (b == 13))) {
            st[0] = (st[0] + 1);
            continue;
        }
        if ((b == 10)) {
            st[0] = (st[0] + 1);
            st[1] = (st[1] + 1);
            continue;
        }
        if ((((b == 47) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 47))) {
            while (((st[0] < n) && ((nyx_i64)(p[st[0]]) != 10))) {
                st[0] = (st[0] + 1);
            }
            continue;
        }
        if ((((b == 47) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 42))) {
            nyx_i64 d = 1;
            st[0] = (st[0] + 2);
            while (((st[0] < n) && (d > 0))) {
                nyx_i64 c = (nyx_i64)(p[st[0]]);
                if ((((c == 47) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 42))) {
                    d = (d + 1);
                    st[0] = (st[0] + 2);
                    continue;
                }
                if ((((c == 42) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 47))) {
                    d = (d - 1);
                    st[0] = (st[0] + 2);
                    continue;
                }
                if ((c == 10)) {
                    st[1] = (st[1] + 1);
                }
                st[0] = (st[0] + 1);
            }
            continue;
        }
        scanning = 0;
    }
    st[5] = st[1];
    if (is_idc(b)) {
        nyx_i64 s = st[0];
        while (((st[0] < n) && (is_idc((nyx_i64)(p[st[0]])) || is_dg((nyx_i64)(p[st[0]]))))) {
            st[0] = (st[0] + 1);
        }
        st[6] = s;
        st[7] = (st[0] - s);
        return kwlook(p, s, (st[0] - s));
    }
    if (is_dg(b)) {
        nyx_i64 v = 0;
        if ((((b == 48) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 120))) {
            st[0] = (st[0] + 2);
            while (((st[0] < n) && (is_hx((nyx_i64)(p[st[0]])) || ((nyx_i64)(p[st[0]]) == 95)))) {
                nyx_i64 d = (nyx_i64)(p[st[0]]);
                if ((d != 95)) {
                    v = ((v * 16) + hxv(d));
                }
                st[0] = (st[0] + 1);
            }
            st[6] = v;
            return 1;
        }
        while (((st[0] < n) && (is_dg((nyx_i64)(p[st[0]])) || ((nyx_i64)(p[st[0]]) == 95)))) {
            nyx_i64 d = (nyx_i64)(p[st[0]]);
            if ((d != 95)) {
                v = ((v * 10) + (d - 48));
            }
            st[0] = (st[0] + 1);
        }
        st[6] = v;
        return 1;
    }
    if ((b == 34)) {
        st[0] = (st[0] + 1);
        return scan_string(p, n, st, 0);
    }
    st[0] = (st[0] + 1);
    nyx_i64 b2 = 0;
    if ((st[0] < n)) {
        b2 = (nyx_i64)(p[st[0]]);
    }
    if ((b == 40)) {
        return 37;
    }
    if ((b == 41)) {
        return 38;
    }
    if ((b == 44)) {
        return 41;
    }
    if ((b == 59)) {
        return 42;
    }
    if ((b == 46)) {
        if ((b2 == 46)) {
            st[0] = (st[0] + 1);
            return 30;
        }
        return 68;
    }
    if ((b == 91)) {
        return 34;
    }
    if ((b == 93)) {
        return 35;
    }
    if ((b == 63)) {
        return 69;
    }
    if ((b == 94)) {
        return 65;
    }
    if ((b == 37)) {
        return 51;
    }
    if ((b == 42)) {
        return 49;
    }
    if ((b == 47)) {
        return 50;
    }
    if ((b == 123)) {
        st[3] = (st[3] + 1);
        return 39;
    }
    if ((b == 125)) {
        if (((st[2] >= 0) && (st[3] == st[(8 + st[2])]))) {
            st[2] = (st[2] - 1);
            st[4] = 1;
            return 6;
        }
        st[3] = (st[3] - 1);
        return 40;
    }
    if ((b == 58)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 44;
        }
        return 43;
    }
    if ((b == 45)) {
        if ((b2 == 62)) {
            st[0] = (st[0] + 1);
            return 45;
        }
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 53;
        }
        return 48;
    }
    if ((b == 43)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 52;
        }
        return 47;
    }
    if ((b == 61)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 54;
        }
        if ((b2 == 62)) {
            st[0] = (st[0] + 1);
            return 26;
        }
        return 46;
    }
    if ((b == 33)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 55;
        }
        return 60;
    }
    if ((b == 60)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 57;
        }
        if ((b2 == 60)) {
            st[0] = (st[0] + 1);
            return 66;
        }
        return 56;
    }
    if ((b == 62)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 59;
        }
        if ((b2 == 62)) {
            st[0] = (st[0] + 1);
            return 67;
        }
        return 58;
    }
    if ((b == 38)) {
        if ((b2 == 38)) {
            st[0] = (st[0] + 1);
            return 61;
        }
        return 63;
    }
    if ((b == 124)) {
        if ((b2 == 124)) {
            st[0] = (st[0] + 1);
            return 62;
        }
        return 64;
    }
    if ((b == 35)) {
        if ((((st[0] + 6) <= n) && eq6(p, st[0], 91, 117, 115, 101, 114, 93))) {
            st[0] = (st[0] + 6);
            return 31;
        }
        if (((((st[0] + 15) <= n) && eq8(p, st[0], 91, 99, 97, 112, 115, 40, 115, 121)) && eq7(p, (st[0] + 8), 115, 99, 97, 108, 108, 41, 93))) {
            st[0] = (st[0] + 15);
            return 32;
        }
        if ((((st[0] + 6) <= n) && eq6(p, st[0], 91, 100, 114, 111, 112, 40))) {
            st[0] = (st[0] + 6);
            nyx_i64 s2 = st[0];
            nyx_bool got = 0;
            while (((st[0] < n) && (is_idc((nyx_i64)(p[st[0]])) || is_dg((nyx_i64)(p[st[0]]))))) {
                st[0] = (st[0] + 1);
                got = 1;
            }
            if (!(got)) {
                return -(1);
            }
            if (((st[0] + 2) > n)) {
                return -(1);
            }
            if (!((((nyx_i64)(p[st[0]]) == 41) && ((nyx_i64)(p[(st[0] + 1)]) == 93)))) {
                return -(1);
            }
            st[6] = s2;
            st[7] = (st[0] - s2);
            st[0] = (st[0] + 2);
            return 33;
        }
        return -(1);
    }
    return -(1);
}

void dump_tok(nyx_u8* p, nyx_i64* st, nyx_i64 k) {
    nyx_i64 l = st[5];
    if (((k == 7) || (k == 33))) {
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(k));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(l));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        put(__s0);
        write(1, (nyx_u8*)(((nyx_addr)(p) + (nyx_addr)(st[6]))), (nyx_isize)(st[7]));
        put(((nyx_str){"\n", 1}));
        return;
    }
    if ((k == 1)) {
        nyx_i64 v = st[6];
        char __b1[256];
        nyx_str __s1 = __nyx_fmt_begin(__b1, 256);
        __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(k));
        __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(l));
        __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(v));
        __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){"\n", 1});
        put(__s1);
        return;
    }
    if (((k >= 2) && (k <= 5))) {
        nyx_i64 c = st[6];
        char __b2[256];
        nyx_str __s2 = __nyx_fmt_begin(__b2, 256);
        __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(k));
        __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(l));
        __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){" #", 2});
        __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(c));
        __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){"\n", 1});
        put(__s2);
        return;
    }
    char __b3[256];
    nyx_str __s3 = __nyx_fmt_begin(__b3, 256);
    __nyx_fmt_i64(&__s3, __b3, 256, (nyx_i64)(k));
    __nyx_fmt_str(&__s3, __b3, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s3, __b3, 256, (nyx_i64)(l));
    __nyx_fmt_str(&__s3, __b3, 256, (nyx_str){"\n", 1});
    put(__s3);
}

nyx_i64 main(nyx_i64 __argc, nyx_u8** __argv) {
    __nyx_args_set(__argc, __argv);
    nyx_str path = ((nyx_str){"/tmp/n_lex_target.n", 19});
    if ((nyx_arg_count() > 1)) {
        path = nyx_arg(1);
    }
    nyx_i64 fd = sys_open((nyx_u8*)(((nyx_u8*)path.ptr)), 0, 0);
    if ((fd < 0)) {
        put(((nyx_str){"(no lex target - skipped)\n", 26}));
        return 0;
    }
    nyx_u8* buf = (nyx_u8*)(sys_sbrk(262144));
    nyx_i64 total = 0;
    nyx_i64 r = 1;
    while ((r > 0)) {
        r = sys_read(fd, (nyx_u8*)(((nyx_addr)(buf) + (nyx_addr)(total))), 16384);
        if ((r > 0)) {
            total = (total + r);
        }
    }
    sys_close(fd);
    if ((total < 1)) {
        return 0;
    }
    nyx_i64* st = (nyx_i64*)(sys_sbrk(256));
    st[0] = 0;
    st[1] = 1;
    st[2] = -(1);
    st[3] = 0;
    st[4] = 0;
    nyx_i64 k = 1;
    nyx_bool going = 1;
    while (going) {
        k = next_kind(buf, total, st);
        dump_tok(buf, st, k);
        if ((k < 1)) {
            going = 0;
        }
    }
    return 0;
}

/* nyxrt.c — Nyx C runtime implementation. Freestanding, no libc calls. */
#include "nyxrt.h"

/* crt0 publishes the process environment here (it references `environ` on every
 * launch). Cross-compiled N programs link nyxrt INSTEAD of libc, so the symbol
 * must live here too — even though nothing in the N runtime reads it yet.
 * In-OS builds (the `cc` builtin, milestone M3) always link /libc.o, which
 * already defines environ — defining it here too would be a duplicate symbol,
 * so the in-OS (tcc) build leaves it to libc. */
#ifndef __TINYC__
char** environ = 0;
#endif

nyx_str __nyx_fmt_begin(char* buf, nyx_u64 cap) {
    (void)cap;
    if (cap) buf[0] = '\0';
    return (nyx_str){ buf, 0 };
}

/* Append n bytes, always NUL-terminating, never overflowing cap. */
static void nyx_append(nyx_str* d, char* buf, nyx_u64 cap, const char* s, nyx_u64 n) {
    nyx_u64 i = 0;
    while (i < n && d->len + 1 < cap) buf[d->len++] = s[i++];
    if (cap) buf[d->len] = '\0';
    d->ptr = buf;
}

void __nyx_fmt_str(nyx_str* d, char* buf, nyx_u64 cap, nyx_str s) {
    nyx_append(d, buf, cap, s.ptr, s.len);
}

void __nyx_fmt_i64(nyx_str* d, char* buf, nyx_u64 cap, nyx_i64 v) {
    char tmp[24];
    int  ti = 0;
    int  neg = 0;
    nyx_u64 uv;
    if (v < 0) { neg = 1; uv = (nyx_u64)(-(v + 1)) + 1; }  /* handles INT64_MIN */
    else         uv = (nyx_u64)v;
    if (uv == 0) tmp[ti++] = '0';
    while (uv) { tmp[ti++] = (char)('0' + (int)(uv % 10)); uv /= 10; }
    if (neg) tmp[ti++] = '-';
    char out[24];
    int  oi = 0;
    while (ti) out[oi++] = tmp[--ti];   /* reverse */
    nyx_append(d, buf, cap, out, (nyx_u64)oi);
}

/* v0.21 "{expr:wN}" / "{expr:zN}" (optionally composed with x/X): format
 * the number, then right-align it in `width` columns. Zero padding puts
 * the sign FIRST ("-0042", the convention every C formatter follows);
 * space padding puts it with the digits ("  -42"). Hex still shows the
 * u64 bit pattern, so no sign appears in hex mode. A value wider than
 * the field is printed in full — width is a minimum, never a cut. */
void __nyx_fmt_num(nyx_str* d, char* buf, nyx_u64 cap, nyx_i64 v,
                   int hex, int upper, int width, int zero) {
    const char* dig = upper ? "0123456789ABCDEF" : "0123456789abcdef";
    char tmp[24];
    int  ti = 0;
    int  neg = 0;
    nyx_u64 uv;
    if (hex) {
        uv = (nyx_u64)v;
        if (uv == 0) tmp[ti++] = '0';
        while (uv) { tmp[ti++] = dig[uv & 15]; uv >>= 4; }
    } else {
        if (v < 0) { neg = 1; uv = (nyx_u64)(-(v + 1)) + 1; }  /* INT64_MIN-safe */
        else         uv = (nyx_u64)v;
        if (uv == 0) tmp[ti++] = '0';
        while (uv) { tmp[ti++] = (char)('0' + (int)(uv % 10)); uv /= 10; }
    }
    char out[160];
    int  oi = 0;
    int  pad = width - ti - neg;
    if (zero) {
        if (neg) out[oi++] = '-';
        while (pad > 0) { out[oi++] = '0'; pad--; }
    } else {
        while (pad > 0) { out[oi++] = ' '; pad--; }
        if (neg) out[oi++] = '-';
    }
    while (ti) out[oi++] = tmp[--ti];   /* reverse the digits */
    nyx_append(d, buf, cap, out, (nyx_u64)oi);
}

/* v0.20 "{expr:x}" / "{expr:X}": hex shows the raw bit pattern, so the
 * value arrives as u64 — a negative i64 prints as its two's-complement
 * image, the reading a systems programmer expects from hex. */
void __nyx_fmt_hex(nyx_str* d, char* buf, nyx_u64 cap, nyx_u64 v, int upper) {
    const char* dig = upper ? "0123456789ABCDEF" : "0123456789abcdef";
    char tmp[16];
    int  ti = 0;
    if (v == 0) tmp[ti++] = '0';
    while (v) { tmp[ti++] = dig[v & 15]; v >>= 4; }
    char out[16];
    int  oi = 0;
    while (ti) out[oi++] = tmp[--ti];   /* reverse */
    nyx_append(d, buf, cap, out, (nyx_u64)oi);
}
