/* Generated by ncc from parse.n */
#include "nyxrt.h"

typedef struct {
    nyx_i64 pt;
    nyx_i64 us;
    nyx_i64 s;
    nyx_i64 l;
} T;

static inline nyx_i64 write(nyx_i32 fd, nyx_u8* buf, nyx_isize len) {
    return (nyx_i64)__nyx_syscall6(1, (nyx_i64)fd, (nyx_i64)buf, (nyx_i64)len, 0, 0, 0);
}
static inline nyx_i64 sys_open(nyx_u8* path, nyx_i64 flags, nyx_i64 mode) {
    return (nyx_i64)__nyx_syscall6(3, (nyx_i64)path, (nyx_i64)flags, (nyx_i64)mode, 0, 0, 0);
}
static inline nyx_i64 sys_read(nyx_i64 fd, nyx_u8* buf, nyx_isize len) {
    return (nyx_i64)__nyx_syscall6(4, (nyx_i64)fd, (nyx_i64)buf, (nyx_i64)len, 0, 0, 0);
}
static inline nyx_i64 sys_close(nyx_i64 fd) {
    return (nyx_i64)__nyx_syscall6(5, (nyx_i64)fd, 0, 0, 0, 0, 0);
}
static inline nyx_i64 sys_sbrk(nyx_i64 incr) {
    return (nyx_i64)__nyx_syscall6(7, (nyx_i64)incr, 0, 0, 0, 0, 0);
}

void put(nyx_str s);
void put_span(nyx_u8* p, nyx_i64 s, nyx_i64 l);
nyx_bool is_idc(nyx_i64 b);
nyx_bool is_dg(nyx_i64 b);
nyx_bool is_hx(nyx_i64 b);
nyx_i64 hxv(nyx_i64 d);
nyx_bool eq2(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b);
nyx_bool eq3(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c);
nyx_bool eq4(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d);
nyx_bool eq5(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e);
nyx_bool eq6(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f);
nyx_bool eq7(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g);
nyx_bool eq8(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g, nyx_i64 h);
nyx_i64 kwlook(nyx_u8* p, nyx_i64 s, nyx_i64 n);
nyx_i64 scan_string(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 cont);
nyx_i64 next_kind(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void adv(nyx_u8* p, nyx_i64 n, nyx_i64* st);
nyx_bool ck(nyx_i64* st, nyx_i64 k);
nyx_bool ck2(nyx_i64* st, nyx_i64 k);
nyx_bool acc(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 k);
void perr(nyx_i64* st);
T pty(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void put_ty(nyx_u8* p, T t);
void pexpr(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pinterp(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pprimary(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void ppostfix(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void ppostfix_tail(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pfield_or_call(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 fs, nyx_i64 fl);
void punary(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pcast(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pmul(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void padd2(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pshift(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pband(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pbxor(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pbor(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pcmp(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pand(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void por(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pmatch(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 exprarms, nyx_i64 mt, nyx_i64 ns2, nyx_i64 nl2, nyx_i64 aop);
void pif(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pblock(nyx_u8* p, nyx_i64 n, nyx_i64* st);
nyx_i64 pparams(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64* ps);
void put_params(nyx_u8* p, nyx_i64* ps, nyx_i64 np);
void skip_item(nyx_u8* p, nyx_i64 n, nyx_i64* st);
void pstruct(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 isown, nyx_i64 hasdrop, nyx_i64 ds, nyx_i64 dl, nyx_i64* ps);
void penum(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64* ps);
void pextern(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 caps, nyx_i64* ps);
void pfn(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 caps, nyx_i64* ps);
void pimpl(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64* ps);
void pass_items(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 which, nyx_i64* ps);
nyx_i64 main(nyx_i64 __argc, nyx_u8** __argv);

void put(nyx_str s) {
    write(1, (nyx_u8*)(((nyx_u8*)s.ptr)), (nyx_isize)(s.len));
}

void put_span(nyx_u8* p, nyx_i64 s, nyx_i64 l) {
    write(1, (nyx_u8*)(((nyx_addr)(p) + (nyx_addr)(s))), (nyx_isize)(l));
}

nyx_bool is_idc(nyx_i64 b) {
    return ((((b >= 97) && (b <= 122)) || ((b >= 65) && (b <= 90))) || (b == 95));
}

nyx_bool is_dg(nyx_i64 b) {
    return ((b >= 48) && (b <= 57));
}

nyx_bool is_hx(nyx_i64 b) {
    return ((is_dg(b) || ((b >= 97) && (b <= 102))) || ((b >= 65) && (b <= 70)));
}

nyx_i64 hxv(nyx_i64 d) {
    if (is_dg(d)) {
        return (d - 48);
    }
    if ((d >= 97)) {
        return (d - 87);
    }
    return (d - 55);
}

nyx_bool eq2(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b) {
    return (((nyx_i64)(p[s]) == a) && ((nyx_i64)(p[(s + 1)]) == b));
}

nyx_bool eq3(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c) {
    return (eq2(p, s, a, b) && ((nyx_i64)(p[(s + 2)]) == c));
}

nyx_bool eq4(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d) {
    return (eq3(p, s, a, b, c) && ((nyx_i64)(p[(s + 3)]) == d));
}

nyx_bool eq5(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e) {
    return (eq4(p, s, a, b, c, d) && ((nyx_i64)(p[(s + 4)]) == e));
}

nyx_bool eq6(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f) {
    return (eq5(p, s, a, b, c, d, e) && ((nyx_i64)(p[(s + 5)]) == f));
}

nyx_bool eq7(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g) {
    return (eq6(p, s, a, b, c, d, e, f) && ((nyx_i64)(p[(s + 6)]) == g));
}

nyx_bool eq8(nyx_u8* p, nyx_i64 s, nyx_i64 a, nyx_i64 b, nyx_i64 c, nyx_i64 d, nyx_i64 e, nyx_i64 f, nyx_i64 g, nyx_i64 h) {
    return (eq7(p, s, a, b, c, d, e, f, g) && ((nyx_i64)(p[(s + 7)]) == h));
}

nyx_i64 kwlook(nyx_u8* p, nyx_i64 s, nyx_i64 n) {
    if ((n == 2)) {
        if (eq2(p, s, 102, 110)) {
            return 10;
        }
        if (eq2(p, s, 97, 115)) {
            return 18;
        }
        if (eq2(p, s, 105, 102)) {
            return 13;
        }
        if (eq2(p, s, 105, 110)) {
            return 29;
        }
    }
    if ((n == 3)) {
        if (eq3(p, s, 109, 117, 116)) {
            return 11;
        }
        if (eq3(p, s, 114, 97, 119)) {
            return 19;
        }
        if (eq3(p, s, 102, 111, 114)) {
            return 28;
        }
        if (eq3(p, s, 111, 119, 110)) {
            return 36;
        }
    }
    if ((n == 4)) {
        if (eq4(p, s, 101, 108, 115, 101)) {
            return 14;
        }
        if (eq4(p, s, 116, 114, 117, 101)) {
            return 20;
        }
        if (eq4(p, s, 101, 110, 117, 109)) {
            return 24;
        }
        if (eq4(p, s, 105, 109, 112, 108)) {
            return 27;
        }
    }
    if ((n == 5)) {
        if (eq5(p, s, 119, 104, 105, 108, 101)) {
            return 15;
        }
        if (eq5(p, s, 98, 114, 101, 97, 107)) {
            return 16;
        }
        if (eq5(p, s, 102, 97, 108, 115, 101)) {
            return 21;
        }
        if (eq5(p, s, 100, 101, 102, 101, 114)) {
            return 23;
        }
        if (eq5(p, s, 109, 97, 116, 99, 104)) {
            return 25;
        }
    }
    if ((n == 6)) {
        if (eq6(p, s, 101, 120, 116, 101, 114, 110)) {
            return 8;
        }
        if (eq6(p, s, 115, 116, 114, 117, 99, 116)) {
            return 22;
        }
        if (eq6(p, s, 114, 101, 116, 117, 114, 110)) {
            return 12;
        }
    }
    if ((n == 7)) {
        if (eq7(p, s, 115, 121, 115, 99, 97, 108, 108)) {
            return 9;
        }
    }
    if ((n == 8)) {
        if (eq8(p, s, 99, 111, 110, 116, 105, 110, 117, 101)) {
            return 17;
        }
    }
    return 7;
}

nyx_i64 scan_string(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 cont) {
    st[5] = st[1];
    nyx_i64 cnt = 0;
    nyx_bool going = 1;
    while (going) {
        if ((st[0] >= n)) {
            return -(1);
        }
        nyx_i64 b = (nyx_i64)(p[st[0]]);
        if ((b == 34)) {
            st[0] = (st[0] + 1);
            st[6] = cnt;
            if ((cont == 1)) {
                return 5;
            }
            return 2;
        }
        if ((b == 123)) {
            st[0] = (st[0] + 1);
            if (((st[2] + 1) >= 16)) {
                return -(1);
            }
            st[2] = (st[2] + 1);
            st[(8 + st[2])] = st[3];
            st[6] = cnt;
            if ((cont == 1)) {
                return 4;
            }
            return 3;
        }
        if ((b == 92)) {
            st[0] = (st[0] + 1);
            if ((st[0] >= n)) {
                return -(1);
            }
            nyx_i64 e = (nyx_i64)(p[st[0]]);
            st[0] = (st[0] + 1);
            nyx_bool ok = (((((((((e == 110) || (e == 116)) || (e == 114)) || (e == 48)) || (e == 92)) || (e == 34)) || (e == 39)) || (e == 123)) || (e == 125));
            if (!(ok)) {
                return -(1);
            }
            cnt = (cnt + 1);
            continue;
        }
        if ((b == 10)) {
            st[1] = (st[1] + 1);
        }
        cnt = (cnt + 1);
        st[0] = (st[0] + 1);
    }
    return 0;
}

nyx_i64 next_kind(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    if ((st[4] == 1)) {
        st[4] = 0;
        return scan_string(p, n, st, 1);
    }
    nyx_i64 b = 0;
    nyx_bool scanning = 1;
    while (scanning) {
        if ((st[0] >= n)) {
            st[5] = st[1];
            return 0;
        }
        b = (nyx_i64)(p[st[0]]);
        if ((((b == 32) || (b == 9)) || (b == 13))) {
            st[0] = (st[0] + 1);
            continue;
        }
        if ((b == 10)) {
            st[0] = (st[0] + 1);
            st[1] = (st[1] + 1);
            continue;
        }
        if ((((b == 47) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 47))) {
            while (((st[0] < n) && ((nyx_i64)(p[st[0]]) != 10))) {
                st[0] = (st[0] + 1);
            }
            continue;
        }
        if ((((b == 47) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 42))) {
            nyx_i64 d = 1;
            st[0] = (st[0] + 2);
            while (((st[0] < n) && (d > 0))) {
                nyx_i64 c = (nyx_i64)(p[st[0]]);
                if ((((c == 47) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 42))) {
                    d = (d + 1);
                    st[0] = (st[0] + 2);
                    continue;
                }
                if ((((c == 42) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 47))) {
                    d = (d - 1);
                    st[0] = (st[0] + 2);
                    continue;
                }
                if ((c == 10)) {
                    st[1] = (st[1] + 1);
                }
                st[0] = (st[0] + 1);
            }
            continue;
        }
        scanning = 0;
    }
    st[5] = st[1];
    if (is_idc(b)) {
        nyx_i64 s = st[0];
        while (((st[0] < n) && (is_idc((nyx_i64)(p[st[0]])) || is_dg((nyx_i64)(p[st[0]]))))) {
            st[0] = (st[0] + 1);
        }
        st[6] = s;
        st[7] = (st[0] - s);
        return kwlook(p, s, (st[0] - s));
    }
    if (is_dg(b)) {
        nyx_i64 v = 0;
        if ((((b == 48) && ((st[0] + 1) < n)) && ((nyx_i64)(p[(st[0] + 1)]) == 120))) {
            st[0] = (st[0] + 2);
            while (((st[0] < n) && (is_hx((nyx_i64)(p[st[0]])) || ((nyx_i64)(p[st[0]]) == 95)))) {
                nyx_i64 d = (nyx_i64)(p[st[0]]);
                if ((d != 95)) {
                    v = ((v * 16) + hxv(d));
                }
                st[0] = (st[0] + 1);
            }
            st[6] = v;
            return 1;
        }
        while (((st[0] < n) && (is_dg((nyx_i64)(p[st[0]])) || ((nyx_i64)(p[st[0]]) == 95)))) {
            nyx_i64 d = (nyx_i64)(p[st[0]]);
            if ((d != 95)) {
                v = ((v * 10) + (d - 48));
            }
            st[0] = (st[0] + 1);
        }
        st[6] = v;
        return 1;
    }
    if ((b == 34)) {
        st[0] = (st[0] + 1);
        return scan_string(p, n, st, 0);
    }
    st[0] = (st[0] + 1);
    nyx_i64 b2 = 0;
    if ((st[0] < n)) {
        b2 = (nyx_i64)(p[st[0]]);
    }
    if ((b == 40)) {
        return 37;
    }
    if ((b == 41)) {
        return 38;
    }
    if ((b == 44)) {
        return 41;
    }
    if ((b == 59)) {
        return 42;
    }
    if ((b == 46)) {
        if ((b2 == 46)) {
            st[0] = (st[0] + 1);
            return 30;
        }
        return 68;
    }
    if ((b == 91)) {
        return 34;
    }
    if ((b == 93)) {
        return 35;
    }
    if ((b == 63)) {
        return 69;
    }
    if ((b == 94)) {
        return 65;
    }
    if ((b == 37)) {
        return 51;
    }
    if ((b == 42)) {
        return 49;
    }
    if ((b == 47)) {
        return 50;
    }
    if ((b == 123)) {
        st[3] = (st[3] + 1);
        return 39;
    }
    if ((b == 125)) {
        if (((st[2] >= 0) && (st[3] == st[(8 + st[2])]))) {
            st[2] = (st[2] - 1);
            st[4] = 1;
            return 6;
        }
        st[3] = (st[3] - 1);
        return 40;
    }
    if ((b == 58)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 44;
        }
        return 43;
    }
    if ((b == 45)) {
        if ((b2 == 62)) {
            st[0] = (st[0] + 1);
            return 45;
        }
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 53;
        }
        return 48;
    }
    if ((b == 43)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 52;
        }
        return 47;
    }
    if ((b == 61)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 54;
        }
        if ((b2 == 62)) {
            st[0] = (st[0] + 1);
            return 26;
        }
        return 46;
    }
    if ((b == 33)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 55;
        }
        return 60;
    }
    if ((b == 60)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 57;
        }
        if ((b2 == 60)) {
            st[0] = (st[0] + 1);
            return 66;
        }
        return 56;
    }
    if ((b == 62)) {
        if ((b2 == 61)) {
            st[0] = (st[0] + 1);
            return 59;
        }
        if ((b2 == 62)) {
            st[0] = (st[0] + 1);
            return 67;
        }
        return 58;
    }
    if ((b == 38)) {
        if ((b2 == 38)) {
            st[0] = (st[0] + 1);
            return 61;
        }
        return 63;
    }
    if ((b == 124)) {
        if ((b2 == 124)) {
            st[0] = (st[0] + 1);
            return 62;
        }
        return 64;
    }
    if ((b == 35)) {
        if ((((st[0] + 6) <= n) && eq6(p, st[0], 91, 117, 115, 101, 114, 93))) {
            st[0] = (st[0] + 6);
            return 31;
        }
        if (((((st[0] + 15) <= n) && eq8(p, st[0], 91, 99, 97, 112, 115, 40, 115, 121)) && eq7(p, (st[0] + 8), 115, 99, 97, 108, 108, 41, 93))) {
            st[0] = (st[0] + 15);
            return 32;
        }
        if ((((st[0] + 6) <= n) && eq6(p, st[0], 91, 100, 114, 111, 112, 40))) {
            st[0] = (st[0] + 6);
            nyx_i64 s2 = st[0];
            nyx_bool got = 0;
            while (((st[0] < n) && (is_idc((nyx_i64)(p[st[0]])) || is_dg((nyx_i64)(p[st[0]]))))) {
                st[0] = (st[0] + 1);
                got = 1;
            }
            if (!(got)) {
                return -(1);
            }
            if (((st[0] + 2) > n)) {
                return -(1);
            }
            if (!((((nyx_i64)(p[st[0]]) == 41) && ((nyx_i64)(p[(st[0] + 1)]) == 93)))) {
                return -(1);
            }
            st[6] = s2;
            st[7] = (st[0] - s2);
            st[0] = (st[0] + 2);
            return 33;
        }
        return -(1);
    }
    return -(1);
}

void adv(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    st[24] = st[28];
    st[25] = st[29];
    st[26] = st[30];
    st[27] = st[31];
    nyx_i64 k = next_kind(p, n, st);
    st[28] = k;
    st[29] = st[5];
    st[30] = st[6];
    st[31] = st[7];
}

nyx_bool ck(nyx_i64* st, nyx_i64 k) {
    return (st[24] == k);
}

nyx_bool ck2(nyx_i64* st, nyx_i64 k) {
    return (st[28] == k);
}

nyx_bool acc(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 k) {
    if ((st[24] == k)) {
        adv(p, n, st);
        return 1;
    }
    return 0;
}

void perr(nyx_i64* st) {
    nyx_i64 l = st[25];
    char __b0[256];
    nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"PARSE-ERR ", 10});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(l));
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"\n", 1});
    put(__s0);
}

T pty(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    nyx_i64 us = 0;
    if (acc(p, n, st, 31)) {
        us = 1;
    }
    if (ck(st, 19)) {
        adv(p, n, st);
    }
    nyx_i64 pt = 0;
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 49)) {
            adv(p, n, st);
            pt = (pt + 1);
            going = 1;
        }
    }
    if (!(ck(st, 7))) {
        perr(st);
        return ((T){.pt = 0, .us = 0, .s = 0, .l = 0});
    }
    nyx_i64 s = st[26];
    nyx_i64 l = st[27];
    adv(p, n, st);
    return ((T){.pt = pt, .us = us, .s = s, .l = l});
}

void put_ty(nyx_u8* p, T t) {
    nyx_i64 pt = t.pt;
    nyx_i64 us = t.us;
    char __b0[256];
    nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(pt));
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){":", 1});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(us));
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){":", 1});
    put(__s0);
    put_span(p, t.s, t.l);
}

void pexpr(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    por(p, n, st);
}

void pinterp(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    nyx_i64* fr = (nyx_i64*)(sys_sbrk(2048));
    nyx_i64 nf = 0;
    fr[0] = 0;
    fr[1] = st[26];
    nf = 1;
    adv(p, n, st);
    nyx_bool going = 1;
    while (going) {
        nyx_i64 fmt = 0;
        nyx_i64 wid = 0;
        nyx_i64 zer = 0;
        pexpr(p, n, st);
        if (acc(p, n, st, 43)) {
            nyx_i64 ss = st[26];
            nyx_i64 sl = st[27];
            if (!(ck(st, 7))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            nyx_i64 i = 0;
            nyx_i64 c0 = (nyx_i64)(p[ss]);
            if (((c0 == 119) || (c0 == 122))) {
                if ((c0 == 122)) {
                    zer = 1;
                }
                i = 1;
                nyx_i64 wd = 0;
                while (((i < sl) && is_dg((nyx_i64)(p[(ss + i)])))) {
                    wd = ((wd * 10) + ((nyx_i64)(p[(ss + i)]) - 48));
                    i = (i + 1);
                }
                wid = wd;
            }
            if (((i < sl) && ((nyx_i64)(p[(ss + i)]) == 120))) {
                fmt = 1;
                i = (i + 1);
            }
            if (((i < sl) && ((nyx_i64)(p[(ss + i)]) == 88))) {
                fmt = 2;
                i = (i + 1);
            }
        }
        fr[(nf * 4)] = 1;
        fr[((nf * 4) + 1)] = fmt;
        fr[((nf * 4) + 2)] = wid;
        fr[((nf * 4) + 3)] = zer;
        nf = (nf + 1);
        if (!(ck(st, 6))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        if (ck(st, 4)) {
            fr[(nf * 4)] = 0;
            fr[((nf * 4) + 1)] = st[26];
            nf = (nf + 1);
            adv(p, n, st);
            continue;
        }
        if (ck(st, 5)) {
            fr[(nf * 4)] = 0;
            fr[((nf * 4) + 1)] = st[26];
            nf = (nf + 1);
            adv(p, n, st);
            going = 0;
            continue;
        }
        perr(st);
        return;
    }
    char __b0[256];
    nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"E 3 ", 4});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(nf));
    put(__s0);
    nyx_i64 q = 0;
    while ((q < nf)) {
        if ((fr[(q * 4)] == 1)) {
            nyx_i64 f = fr[((q * 4) + 1)];
            nyx_i64 w = fr[((q * 4) + 2)];
            nyx_i64 z = fr[((q * 4) + 3)];
            char __b1[256];
            nyx_str __s1 = __nyx_fmt_begin(__b1, 256);
            __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){" @", 2});
            __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(f));
            __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){".", 1});
            __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(w));
            __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){".", 1});
            __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(z));
            put(__s1);
        }
        if ((fr[(q * 4)] == 0)) {
            nyx_i64 t = fr[((q * 4) + 1)];
            char __b2[256];
            nyx_str __s2 = __nyx_fmt_begin(__b2, 256);
            __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){" #", 2});
            __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(t));
            put(__s2);
        }
        q = (q + 1);
    }
    put(((nyx_str){"\n", 1}));
}

void pprimary(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    if (ck(st, 1)) {
        nyx_i64 v = st[26];
        adv(p, n, st);
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"E 0 ", 4});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(v));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"\n", 1});
        put(__s0);
        return;
    }
    if ((ck(st, 20) || ck(st, 21))) {
        nyx_i64 v = 0;
        if (ck(st, 20)) {
            v = 1;
        }
        adv(p, n, st);
        char __b1[256];
        nyx_str __s1 = __nyx_fmt_begin(__b1, 256);
        __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){"E 1 ", 4});
        __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(v));
        __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){"\n", 1});
        put(__s1);
        return;
    }
    if (ck(st, 2)) {
        nyx_i64 c = st[26];
        adv(p, n, st);
        char __b2[256];
        nyx_str __s2 = __nyx_fmt_begin(__b2, 256);
        __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){"E 2 #", 5});
        __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(c));
        __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){"\n", 1});
        put(__s2);
        return;
    }
    if (ck(st, 3)) {
        pinterp(p, n, st);
        return;
    }
    if (ck(st, 37)) {
        adv(p, n, st);
        nyx_i64 save = st[32];
        st[32] = 0;
        pexpr(p, n, st);
        st[32] = save;
        if (!(ck(st, 38))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        return;
    }
    if (ck(st, 7)) {
        nyx_i64 ns = st[26];
        nyx_i64 nl = st[27];
        adv(p, n, st);
        if ((ck(st, 39) && (st[32] == 0))) {
            adv(p, n, st);
            nyx_i64* fs = (nyx_i64*)(sys_sbrk(256));
            nyx_i64 na = 0;
            nyx_bool more = !(ck(st, 40));
            while (more) {
                more = 0;
                if (ck(st, 40)) {
                    continue;
                }
                if (!(ck(st, 7))) {
                    perr(st);
                    return;
                }
                fs[(na * 2)] = st[26];
                fs[((na * 2) + 1)] = st[27];
                adv(p, n, st);
                if (!(ck(st, 43))) {
                    perr(st);
                    return;
                }
                adv(p, n, st);
                pexpr(p, n, st);
                na = (na + 1);
                if (acc(p, n, st, 41)) {
                    more = 1;
                }
            }
            if (!(ck(st, 40))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            char __b3[256];
            nyx_str __s3 = __nyx_fmt_begin(__b3, 256);
            __nyx_fmt_str(&__s3, __b3, 256, (nyx_str){"E 10 ", 5});
            __nyx_fmt_i64(&__s3, __b3, 256, (nyx_i64)(na));
            __nyx_fmt_str(&__s3, __b3, 256, (nyx_str){" ", 1});
            put(__s3);
            put_span(p, ns, nl);
            nyx_i64 q = 0;
            while ((q < na)) {
                put(((nyx_str){" ", 1}));
                put_span(p, fs[(q * 2)], fs[((q * 2) + 1)]);
                q = (q + 1);
            }
            put(((nyx_str){"\n", 1}));
            return;
        }
        put(((nyx_str){"E 4 ", 4}));
        put_span(p, ns, nl);
        put(((nyx_str){"\n", 1}));
        return;
    }
    perr(st);
}

void ppostfix(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    if ((ck(st, 7) && ck2(st, 68))) {
        nyx_i64 ns = st[26];
        nyx_i64 nl = st[27];
        adv(p, n, st);
        adv(p, n, st);
        if (!(ck(st, 7))) {
            perr(st);
            return;
        }
        nyx_i64 fs = st[26];
        nyx_i64 fl = st[27];
        adv(p, n, st);
        if ((ck(st, 39) && (st[32] == 0))) {
            adv(p, n, st);
            nyx_i64* fns = (nyx_i64*)(sys_sbrk(256));
            nyx_i64 na = 0;
            nyx_bool more = !(ck(st, 40));
            while (more) {
                more = 0;
                if (ck(st, 40)) {
                    continue;
                }
                if (!(ck(st, 7))) {
                    perr(st);
                    return;
                }
                fns[(na * 2)] = st[26];
                fns[((na * 2) + 1)] = st[27];
                adv(p, n, st);
                if (!(ck(st, 43))) {
                    perr(st);
                    return;
                }
                adv(p, n, st);
                pexpr(p, n, st);
                na = (na + 1);
                if (acc(p, n, st, 41)) {
                    more = 1;
                }
            }
            if (!(ck(st, 40))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            char __b0[256];
            nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
            __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"E 11 ", 5});
            __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(na));
            __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
            put(__s0);
            put_span(p, ns, nl);
            put(((nyx_str){" ", 1}));
            put_span(p, fs, fl);
            nyx_i64 q = 0;
            while ((q < na)) {
                put(((nyx_str){" ", 1}));
                put_span(p, fns[(q * 2)], fns[((q * 2) + 1)]);
                q = (q + 1);
            }
            put(((nyx_str){"\n", 1}));
            ppostfix_tail(p, n, st);
            return;
        }
        put(((nyx_str){"E 4 ", 4}));
        put_span(p, ns, nl);
        put(((nyx_str){"\n", 1}));
        pfield_or_call(p, n, st, fs, fl);
        ppostfix_tail(p, n, st);
        return;
    }
    pprimary(p, n, st);
    ppostfix_tail(p, n, st);
}

void ppostfix_tail(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 68)) {
            adv(p, n, st);
            if (!(ck(st, 7))) {
                perr(st);
                return;
            }
            nyx_i64 fs = st[26];
            nyx_i64 fl = st[27];
            adv(p, n, st);
            pfield_or_call(p, n, st, fs, fl);
            going = 1;
            continue;
        }
        if (ck(st, 37)) {
            adv(p, n, st);
            nyx_i64 na = 0;
            nyx_bool more = !(ck(st, 38));
            while (more) {
                more = 0;
                pexpr(p, n, st);
                na = (na + 1);
                if (acc(p, n, st, 41)) {
                    more = 1;
                }
            }
            if (!(ck(st, 38))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            char __b0[256];
            nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
            __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"E 5 ", 4});
            __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(na));
            __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"\n", 1});
            put(__s0);
            going = 1;
            continue;
        }
        if (ck(st, 34)) {
            adv(p, n, st);
            pexpr(p, n, st);
            if (!(ck(st, 35))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            put(((nyx_str){"E 12\n", 5}));
            going = 1;
            continue;
        }
    }
}

void pfield_or_call(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 fs, nyx_i64 fl) {
    if (ck(st, 37)) {
        put(((nyx_str){"E 6 ", 4}));
        put_span(p, fs, fl);
        put(((nyx_str){"\n", 1}));
        adv(p, n, st);
        nyx_i64 na = 0;
        nyx_bool more = !(ck(st, 38));
        while (more) {
            more = 0;
            pexpr(p, n, st);
            na = (na + 1);
            if (acc(p, n, st, 41)) {
                more = 1;
            }
        }
        if (!(ck(st, 38))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"E 5 ", 4});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(na));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"\n", 1});
        put(__s0);
        return;
    }
    put(((nyx_str){"E 6 ", 4}));
    put_span(p, fs, fl);
    put(((nyx_str){"\n", 1}));
}

void punary(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    if (ck(st, 48)) {
        adv(p, n, st);
        punary(p, n, st);
        put(((nyx_str){"E 7 -\n", 6}));
        return;
    }
    if (ck(st, 60)) {
        adv(p, n, st);
        punary(p, n, st);
        put(((nyx_str){"E 7 !\n", 6}));
        return;
    }
    ppostfix(p, n, st);
}

void pcast(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    punary(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 18)) {
            adv(p, n, st);
            T t = pty(p, n, st);
            put(((nyx_str){"E 9", 3}));
            put_ty(p, t);
            put(((nyx_str){"\n", 1}));
            going = 1;
        }
    }
}

void pmul(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pcast(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 49)) {
            adv(p, n, st);
            pcast(p, n, st);
            put(((nyx_str){"E 8 *\n", 6}));
            going = 1;
            continue;
        }
        if (ck(st, 50)) {
            adv(p, n, st);
            pcast(p, n, st);
            put(((nyx_str){"E 8 /\n", 6}));
            going = 1;
            continue;
        }
        if (ck(st, 51)) {
            adv(p, n, st);
            pcast(p, n, st);
            put(((nyx_str){"E 8 %\n", 6}));
            going = 1;
        }
    }
}

void padd2(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pmul(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 47)) {
            adv(p, n, st);
            pmul(p, n, st);
            put(((nyx_str){"E 8 +\n", 6}));
            going = 1;
            continue;
        }
        if (ck(st, 48)) {
            adv(p, n, st);
            pmul(p, n, st);
            put(((nyx_str){"E 8 -\n", 6}));
            going = 1;
        }
    }
}

void pshift(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    padd2(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 66)) {
            adv(p, n, st);
            padd2(p, n, st);
            put(((nyx_str){"E 8 <<\n", 7}));
            going = 1;
            continue;
        }
        if (ck(st, 67)) {
            adv(p, n, st);
            padd2(p, n, st);
            put(((nyx_str){"E 8 >>\n", 7}));
            going = 1;
        }
    }
}

void pband(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pshift(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 63)) {
            adv(p, n, st);
            pshift(p, n, st);
            put(((nyx_str){"E 8 &\n", 6}));
            going = 1;
        }
    }
}

void pbxor(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pband(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 65)) {
            adv(p, n, st);
            pband(p, n, st);
            put(((nyx_str){"E 8 ^\n", 6}));
            going = 1;
        }
    }
}

void pbor(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pbxor(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 64)) {
            adv(p, n, st);
            pbxor(p, n, st);
            put(((nyx_str){"E 8 |\n", 6}));
            going = 1;
        }
    }
}

void pcmp(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pbor(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 54)) {
            adv(p, n, st);
            pbor(p, n, st);
            put(((nyx_str){"E 8 ==\n", 7}));
            going = 1;
            continue;
        }
        if (ck(st, 55)) {
            adv(p, n, st);
            pbor(p, n, st);
            put(((nyx_str){"E 8 !=\n", 7}));
            going = 1;
            continue;
        }
        if (ck(st, 56)) {
            adv(p, n, st);
            pbor(p, n, st);
            put(((nyx_str){"E 8 <\n", 6}));
            going = 1;
            continue;
        }
        if (ck(st, 57)) {
            adv(p, n, st);
            pbor(p, n, st);
            put(((nyx_str){"E 8 <=\n", 7}));
            going = 1;
            continue;
        }
        if (ck(st, 58)) {
            adv(p, n, st);
            pbor(p, n, st);
            put(((nyx_str){"E 8 >\n", 6}));
            going = 1;
            continue;
        }
        if (ck(st, 59)) {
            adv(p, n, st);
            pbor(p, n, st);
            put(((nyx_str){"E 8 >=\n", 7}));
            going = 1;
        }
    }
}

void pand(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pcmp(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 61)) {
            adv(p, n, st);
            pcmp(p, n, st);
            put(((nyx_str){"E 8 &&\n", 7}));
            going = 1;
        }
    }
}

void por(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    pand(p, n, st);
    nyx_bool going = 1;
    while (going) {
        going = 0;
        if (ck(st, 62)) {
            adv(p, n, st);
            pand(p, n, st);
            put(((nyx_str){"E 8 ||\n", 7}));
            going = 1;
        }
    }
}

void pmatch(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 exprarms, nyx_i64 mt, nyx_i64 ns2, nyx_i64 nl2, nyx_i64 aop) {
    st[32] = 1;
    pexpr(p, n, st);
    st[32] = 0;
    if (!(ck(st, 39))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    nyx_i64* bs = (nyx_i64*)(sys_sbrk(512));
    nyx_i64 na = 0;
    nyx_bool more = !(ck(st, 40));
    while (more) {
        more = 0;
        if (!(ck(st, 7))) {
            perr(st);
            return;
        }
        nyx_i64 vs = st[26];
        nyx_i64 vl = st[27];
        adv(p, n, st);
        nyx_i64 nb = 0;
        if (acc(p, n, st, 37)) {
            nyx_bool inner = 1;
            while (inner) {
                inner = 0;
                if (!(ck(st, 7))) {
                    perr(st);
                    return;
                }
                bs[(nb * 2)] = st[26];
                bs[((nb * 2) + 1)] = st[27];
                adv(p, n, st);
                nb = (nb + 1);
                if (acc(p, n, st, 41)) {
                    inner = 1;
                }
            }
            if (!(ck(st, 38))) {
                perr(st);
                return;
            }
            adv(p, n, st);
        }
        if (!(ck(st, 26))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        if ((exprarms == 1)) {
            pexpr(p, n, st);
        }
        if ((exprarms == 0)) {
            pblock(p, n, st);
        }
        put(((nyx_str){"A ", 2}));
        put_span(p, vs, vl);
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(nb));
        put(__s0);
        nyx_i64 q = 0;
        while ((q < nb)) {
            put(((nyx_str){" ", 1}));
            put_span(p, bs[(q * 2)], bs[((q * 2) + 1)]);
            q = (q + 1);
        }
        char __b1[256];
        nyx_str __s1 = __nyx_fmt_begin(__b1, 256);
        __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(exprarms));
        __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){"\n", 1});
        put(__s1);
        na = (na + 1);
        if (acc(p, n, st, 41)) {
            if (!(ck(st, 40))) {
                more = 1;
            }
        }
    }
    if (!(ck(st, 40))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    char __b2[256];
    nyx_str __s2 = __nyx_fmt_begin(__b2, 256);
    __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){"S 9 ", 4});
    __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(na));
    __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(mt));
    __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){" ", 1});
    put(__s2);
    if ((nl2 > 0)) {
        put_span(p, ns2, nl2);
    }
    if ((nl2 == 0)) {
        put(((nyx_str){"-", 1}));
    }
    put(((nyx_str){" ", 1}));
    if ((aop == 0)) {
        put(((nyx_str){"-", 1}));
    }
    if ((aop == 1)) {
        put(((nyx_str){"=", 1}));
    }
    if ((aop == 2)) {
        put(((nyx_str){"+=", 2}));
    }
    if ((aop == 3)) {
        put(((nyx_str){"-=", 2}));
    }
    put(((nyx_str){"\n", 1}));
}

void pif(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    adv(p, n, st);
    st[32] = 1;
    pexpr(p, n, st);
    st[32] = 0;
    pblock(p, n, st);
    nyx_i64 has_else = 0;
    if (acc(p, n, st, 14)) {
        has_else = 1;
        nyx_i64 inner = 0;
        if (ck(st, 13)) {
            inner = 1;
            pif(p, n, st);
            put(((nyx_str){"B 1 0\n", 6}));
        }
        if ((inner == 0)) {
            pblock(p, n, st);
        }
    }
    char __b0[256];
    nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"S 5 ", 4});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(has_else));
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"\n", 1});
    put(__s0);
}

void pblock(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    if (!(ck(st, 39))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    nyx_i64 ns = 0;
    nyx_bool going = 1;
    while (going) {
        if (ck(st, 40)) {
            going = 0;
            continue;
        }
        if (ck(st, 0)) {
            perr(st);
            return;
        }
        if ((ck(st, 11) || (ck(st, 7) && ck2(st, 44)))) {
            nyx_i64 im = 0;
            if (acc(p, n, st, 11)) {
                im = 1;
            }
            if (!(ck(st, 7))) {
                perr(st);
                return;
            }
            nyx_i64 is = st[26];
            nyx_i64 il = st[27];
            adv(p, n, st);
            if (!(ck(st, 44))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            if (ck(st, 25)) {
                adv(p, n, st);
                pmatch(p, n, st, 1, 1, is, il, 0);
                if (!(ck(st, 42))) {
                    perr(st);
                    return;
                }
                adv(p, n, st);
                ns = (ns + 1);
                continue;
            }
            pexpr(p, n, st);
            nyx_i64 tr = 0;
            if (acc(p, n, st, 69)) {
                tr = 1;
            }
            if (!(ck(st, 42))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            char __b0[256];
            nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
            __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){"S 0 ", 4});
            __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(im));
            __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
            __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(tr));
            __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
            put(__s0);
            put_span(p, is, il);
            put(((nyx_str){"\n", 1}));
            ns = (ns + 1);
            continue;
        }
        if (acc(p, n, st, 12)) {
            if (ck(st, 25)) {
                adv(p, n, st);
                pmatch(p, n, st, 1, 3, 0, 0, 0);
                if (!(ck(st, 42))) {
                    perr(st);
                    return;
                }
                adv(p, n, st);
                ns = (ns + 1);
                continue;
            }
            if (ck(st, 42)) {
                adv(p, n, st);
                put(((nyx_str){"nil\n", 4}));
                put(((nyx_str){"S 2 0\n", 6}));
                ns = (ns + 1);
                continue;
            }
            pexpr(p, n, st);
            if (!(ck(st, 42))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            put(((nyx_str){"S 2 0\n", 6}));
            ns = (ns + 1);
            continue;
        }
        if (acc(p, n, st, 16)) {
            if (!(ck(st, 42))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            put(((nyx_str){"S 6\n", 4}));
            ns = (ns + 1);
            continue;
        }
        if (acc(p, n, st, 17)) {
            if (!(ck(st, 42))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            put(((nyx_str){"S 7\n", 4}));
            ns = (ns + 1);
            continue;
        }
        if (acc(p, n, st, 23)) {
            pexpr(p, n, st);
            if (!(ck(st, 42))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            put(((nyx_str){"S 8\n", 4}));
            ns = (ns + 1);
            continue;
        }
        if (ck(st, 15)) {
            adv(p, n, st);
            st[32] = 1;
            pexpr(p, n, st);
            st[32] = 0;
            pblock(p, n, st);
            put(((nyx_str){"S 4\n", 4}));
            ns = (ns + 1);
            continue;
        }
        if (ck(st, 13)) {
            pif(p, n, st);
            ns = (ns + 1);
            continue;
        }
        if (ck(st, 25)) {
            adv(p, n, st);
            pmatch(p, n, st, 0, 0, 0, 0, 0);
            ns = (ns + 1);
            continue;
        }
        if (ck(st, 28)) {
            adv(p, n, st);
            if (!(ck(st, 7))) {
                perr(st);
                return;
            }
            nyx_i64 fs2 = st[26];
            nyx_i64 fl2 = st[27];
            adv(p, n, st);
            if (!(ck(st, 29))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            st[32] = 1;
            pexpr(p, n, st);
            if (!(ck(st, 30))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            pexpr(p, n, st);
            st[32] = 0;
            pblock(p, n, st);
            put(((nyx_str){"S 10 ", 5}));
            put_span(p, fs2, fl2);
            put(((nyx_str){"\n", 1}));
            ns = (ns + 1);
            continue;
        }
        pexpr(p, n, st);
        if (((ck(st, 46) || ck(st, 52)) || ck(st, 53))) {
            nyx_i64 op = 0;
            if (ck(st, 52)) {
                op = 1;
            }
            if (ck(st, 53)) {
                op = 2;
            }
            adv(p, n, st);
            if (ck(st, 25)) {
                adv(p, n, st);
                pmatch(p, n, st, 1, 2, 0, 0, (op + 1));
                if (!(ck(st, 42))) {
                    perr(st);
                    return;
                }
                adv(p, n, st);
                ns = (ns + 1);
                continue;
            }
            pexpr(p, n, st);
            nyx_i64 tr = 0;
            if (acc(p, n, st, 69)) {
                tr = 1;
            }
            if (!(ck(st, 42))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            if ((op == 0)) {
                char __b1[256];
                nyx_str __s1 = __nyx_fmt_begin(__b1, 256);
                __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){"S 1 ", 4});
                __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(tr));
                __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){" =\n", 3});
                put(__s1);
            }
            if ((op == 1)) {
                char __b2[256];
                nyx_str __s2 = __nyx_fmt_begin(__b2, 256);
                __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){"S 1 ", 4});
                __nyx_fmt_i64(&__s2, __b2, 256, (nyx_i64)(tr));
                __nyx_fmt_str(&__s2, __b2, 256, (nyx_str){" +=\n", 4});
                put(__s2);
            }
            if ((op == 2)) {
                char __b3[256];
                nyx_str __s3 = __nyx_fmt_begin(__b3, 256);
                __nyx_fmt_str(&__s3, __b3, 256, (nyx_str){"S 1 ", 4});
                __nyx_fmt_i64(&__s3, __b3, 256, (nyx_i64)(tr));
                __nyx_fmt_str(&__s3, __b3, 256, (nyx_str){" -=\n", 4});
                put(__s3);
            }
            ns = (ns + 1);
            continue;
        }
        if (acc(p, n, st, 69)) {
            if (!(ck(st, 42))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            put(((nyx_str){"S 3 1\n", 6}));
            ns = (ns + 1);
            continue;
        }
        if (acc(p, n, st, 42)) {
            put(((nyx_str){"S 3 0\n", 6}));
            ns = (ns + 1);
            continue;
        }
        if (ck(st, 40)) {
            adv(p, n, st);
            char __b4[256];
            nyx_str __s4 = __nyx_fmt_begin(__b4, 256);
            __nyx_fmt_str(&__s4, __b4, 256, (nyx_str){"B ", 2});
            __nyx_fmt_i64(&__s4, __b4, 256, (nyx_i64)(ns));
            __nyx_fmt_str(&__s4, __b4, 256, (nyx_str){" 1\n", 3});
            put(__s4);
            return;
        }
        perr(st);
        return;
    }
    adv(p, n, st);
    char __b5[256];
    nyx_str __s5 = __nyx_fmt_begin(__b5, 256);
    __nyx_fmt_str(&__s5, __b5, 256, (nyx_str){"B ", 2});
    __nyx_fmt_i64(&__s5, __b5, 256, (nyx_i64)(ns));
    __nyx_fmt_str(&__s5, __b5, 256, (nyx_str){" 0\n", 3});
    put(__s5);
}

nyx_i64 pparams(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64* ps) {
    if (!(ck(st, 37))) {
        perr(st);
        return 0;
    }
    adv(p, n, st);
    nyx_i64 np = 0;
    nyx_bool more = !(ck(st, 38));
    while (more) {
        more = 0;
        if (!(ck(st, 7))) {
            perr(st);
            return np;
        }
        ps[(np * 6)] = st[26];
        ps[((np * 6) + 1)] = st[27];
        adv(p, n, st);
        if (!(ck(st, 43))) {
            perr(st);
            return np;
        }
        adv(p, n, st);
        T t = pty(p, n, st);
        ps[((np * 6) + 2)] = t.pt;
        ps[((np * 6) + 3)] = t.us;
        ps[((np * 6) + 4)] = t.s;
        ps[((np * 6) + 5)] = t.l;
        np = (np + 1);
        if (acc(p, n, st, 41)) {
            more = 1;
        }
    }
    if (!(ck(st, 38))) {
        perr(st);
        return np;
    }
    adv(p, n, st);
    return np;
}

void put_params(nyx_u8* p, nyx_i64* ps, nyx_i64 np) {
    nyx_i64 q = 0;
    while ((q < np)) {
        put(((nyx_str){" ", 1}));
        put_span(p, ps[(q * 6)], ps[((q * 6) + 1)]);
        nyx_i64 pt = ps[((q * 6) + 2)];
        nyx_i64 us = ps[((q * 6) + 3)];
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(pt));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){":", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(us));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){":", 1});
        put(__s0);
        put_span(p, ps[((q * 6) + 4)], ps[((q * 6) + 5)]);
        q = (q + 1);
    }
}

void skip_item(nyx_u8* p, nyx_i64 n, nyx_i64* st) {
    nyx_bool going = 1;
    while (going) {
        if (ck(st, 0)) {
            return;
        }
        if (ck(st, 39)) {
            going = 0;
            continue;
        }
        adv(p, n, st);
    }
    adv(p, n, st);
    nyx_i64 d = 1;
    while ((d > 0)) {
        if (ck(st, 0)) {
            return;
        }
        if (ck(st, 39)) {
            d = (d + 1);
        }
        if (ck(st, 40)) {
            d = (d - 1);
        }
        adv(p, n, st);
    }
}

void pstruct(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 isown, nyx_i64 hasdrop, nyx_i64 ds, nyx_i64 dl, nyx_i64* ps) {
    if (!(ck(st, 7))) {
        perr(st);
        return;
    }
    nyx_i64 ns = st[26];
    nyx_i64 nl = st[27];
    adv(p, n, st);
    if (!(ck(st, 39))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    nyx_i64 nf = 0;
    nyx_bool more = !(ck(st, 40));
    while (more) {
        more = 0;
        if (!(ck(st, 7))) {
            perr(st);
            return;
        }
        ps[(nf * 6)] = st[26];
        ps[((nf * 6) + 1)] = st[27];
        adv(p, n, st);
        if (!(ck(st, 43))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        T t = pty(p, n, st);
        ps[((nf * 6) + 2)] = t.pt;
        ps[((nf * 6) + 3)] = t.us;
        ps[((nf * 6) + 4)] = t.s;
        ps[((nf * 6) + 5)] = t.l;
        nf = (nf + 1);
        if (acc(p, n, st, 41)) {
            if (!(ck(st, 40))) {
                more = 1;
            }
        }
    }
    if (!(ck(st, 40))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    put(((nyx_str){"D ", 2}));
    put_span(p, ns, nl);
    char __b0[256];
    nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(isown));
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
    put(__s0);
    if ((hasdrop == 1)) {
        put_span(p, ds, dl);
    }
    if ((hasdrop == 0)) {
        put(((nyx_str){"-", 1}));
    }
    char __b1[256];
    nyx_str __s1 = __nyx_fmt_begin(__b1, 256);
    __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(nf));
    put(__s1);
    put_params(p, ps, nf);
    put(((nyx_str){"\n", 1}));
}

void penum(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64* ps) {
    if (!(ck(st, 7))) {
        perr(st);
        return;
    }
    nyx_i64 ns = st[26];
    nyx_i64 nl = st[27];
    adv(p, n, st);
    if (!(ck(st, 39))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    nyx_i64 nv = 0;
    nyx_bool more = !(ck(st, 40));
    while (more) {
        more = 0;
        if (!(ck(st, 7))) {
            perr(st);
            return;
        }
        nyx_i64 vs = st[26];
        nyx_i64 vl = st[27];
        adv(p, n, st);
        nyx_i64 nf = 0;
        if (acc(p, n, st, 37)) {
            nyx_bool inner = 1;
            while (inner) {
                inner = 0;
                if (!(ck(st, 7))) {
                    perr(st);
                    return;
                }
                ps[(nf * 6)] = st[26];
                ps[((nf * 6) + 1)] = st[27];
                adv(p, n, st);
                if (!(ck(st, 43))) {
                    perr(st);
                    return;
                }
                adv(p, n, st);
                T t = pty(p, n, st);
                ps[((nf * 6) + 2)] = t.pt;
                ps[((nf * 6) + 3)] = t.us;
                ps[((nf * 6) + 4)] = t.s;
                ps[((nf * 6) + 5)] = t.l;
                nf = (nf + 1);
                if (acc(p, n, st, 41)) {
                    inner = 1;
                }
            }
            if (!(ck(st, 38))) {
                perr(st);
                return;
            }
            adv(p, n, st);
        }
        put(((nyx_str){"V ", 2}));
        put_span(p, vs, vl);
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(nf));
        put(__s0);
        put_params(p, ps, nf);
        put(((nyx_str){"\n", 1}));
        nv = (nv + 1);
        if (acc(p, n, st, 41)) {
            if (!(ck(st, 40))) {
                more = 1;
            }
        }
    }
    if (!(ck(st, 40))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    put(((nyx_str){"U ", 2}));
    put_span(p, ns, nl);
    char __b1[256];
    nyx_str __s1 = __nyx_fmt_begin(__b1, 256);
    __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s1, __b1, 256, (nyx_i64)(nv));
    __nyx_fmt_str(&__s1, __b1, 256, (nyx_str){"\n", 1});
    put(__s1);
}

void pextern(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 caps, nyx_i64* ps) {
    if (!(ck(st, 9))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    if (!(ck(st, 39))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    nyx_bool more = ck(st, 10);
    while (more) {
        more = 0;
        adv(p, n, st);
        if (!(ck(st, 7))) {
            perr(st);
            return;
        }
        nyx_i64 xs = st[26];
        nyx_i64 xl = st[27];
        adv(p, n, st);
        nyx_i64 np = pparams(p, n, st, ps);
        T rt = ((T){.pt = 0, .us = 0, .s = 0, .l = 0});
        nyx_i64 has_rt = 0;
        if (acc(p, n, st, 45)) {
            rt = pty(p, n, st);
            has_rt = 1;
        }
        if (!(ck(st, 46))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        if (!(ck(st, 1))) {
            perr(st);
            return;
        }
        nyx_i64 num = st[26];
        adv(p, n, st);
        if (ck(st, 42)) {
            adv(p, n, st);
        }
        put(((nyx_str){"X ", 2}));
        put_span(p, xs, xl);
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(num));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(caps));
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(np));
        put(__s0);
        put_params(p, ps, np);
        if ((has_rt == 1)) {
            put_ty(p, rt);
        }
        if ((has_rt == 0)) {
            put(((nyx_str){" 0:0:-", 6}));
        }
        put(((nyx_str){"\n", 1}));
        if (ck(st, 10)) {
            more = 1;
        }
    }
    if (!(ck(st, 40))) {
        perr(st);
        return;
    }
    adv(p, n, st);
}

void pfn(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 caps, nyx_i64* ps) {
    if (!(ck(st, 7))) {
        perr(st);
        return;
    }
    nyx_i64 fs = st[26];
    nyx_i64 fl = st[27];
    adv(p, n, st);
    nyx_i64 np = pparams(p, n, st, ps);
    T rt = ((T){.pt = 0, .us = 0, .s = 0, .l = 0});
    nyx_i64 has_rt = 0;
    if (acc(p, n, st, 45)) {
        rt = pty(p, n, st);
        has_rt = 1;
    }
    pblock(p, n, st);
    put(((nyx_str){"F ", 2}));
    put_span(p, fs, fl);
    char __b0[256];
    nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(caps));
    __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
    __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(np));
    put(__s0);
    put_params(p, ps, np);
    if ((has_rt == 1)) {
        put_ty(p, rt);
    }
    if ((has_rt == 0)) {
        put(((nyx_str){" 0:0:-", 6}));
    }
    put(((nyx_str){"\n", 1}));
}

void pimpl(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64* ps) {
    if (!(ck(st, 7))) {
        perr(st);
        return;
    }
    nyx_i64 ts = st[26];
    nyx_i64 tl = st[27];
    adv(p, n, st);
    if (!(ck(st, 39))) {
        perr(st);
        return;
    }
    adv(p, n, st);
    nyx_bool more = ck(st, 10);
    while (more) {
        more = 0;
        adv(p, n, st);
        if (!(ck(st, 7))) {
            perr(st);
            return;
        }
        nyx_i64 ms = st[26];
        nyx_i64 ml = st[27];
        adv(p, n, st);
        if (!(ck(st, 37))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        if (!(ck(st, 7))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        nyx_i64 np = 0;
        nyx_bool inner = acc(p, n, st, 41);
        while (inner) {
            inner = 0;
            if (!(ck(st, 7))) {
                perr(st);
                return;
            }
            ps[(np * 6)] = st[26];
            ps[((np * 6) + 1)] = st[27];
            adv(p, n, st);
            if (!(ck(st, 43))) {
                perr(st);
                return;
            }
            adv(p, n, st);
            T t = pty(p, n, st);
            ps[((np * 6) + 2)] = t.pt;
            ps[((np * 6) + 3)] = t.us;
            ps[((np * 6) + 4)] = t.s;
            ps[((np * 6) + 5)] = t.l;
            np = (np + 1);
            if (acc(p, n, st, 41)) {
                inner = 1;
            }
        }
        if (!(ck(st, 38))) {
            perr(st);
            return;
        }
        adv(p, n, st);
        T rt = ((T){.pt = 0, .us = 0, .s = 0, .l = 0});
        nyx_i64 has_rt = 0;
        if (acc(p, n, st, 45)) {
            rt = pty(p, n, st);
            has_rt = 1;
        }
        pblock(p, n, st);
        put(((nyx_str){"M ", 2}));
        put_span(p, ts, tl);
        put(((nyx_str){" ", 1}));
        put_span(p, ms, ml);
        char __b0[256];
        nyx_str __s0 = __nyx_fmt_begin(__b0, 256);
        __nyx_fmt_str(&__s0, __b0, 256, (nyx_str){" ", 1});
        __nyx_fmt_i64(&__s0, __b0, 256, (nyx_i64)(np));
        put(__s0);
        put_params(p, ps, np);
        if ((has_rt == 1)) {
            put_ty(p, rt);
        }
        if ((has_rt == 0)) {
            put(((nyx_str){" 0:0:-", 6}));
        }
        put(((nyx_str){"\n", 1}));
        if (ck(st, 10)) {
            more = 1;
        }
    }
    if (!(ck(st, 40))) {
        perr(st);
        return;
    }
    adv(p, n, st);
}

void pass_items(nyx_u8* p, nyx_i64 n, nyx_i64* st, nyx_i64 which, nyx_i64* ps) {
    nyx_bool going = 1;
    while (going) {
        if (ck(st, 0)) {
            going = 0;
            continue;
        }
        nyx_i64 caps = 0;
        nyx_i64 isown = 0;
        nyx_i64 hasdrop = 0;
        nyx_i64 ds = 0;
        nyx_i64 dl = 0;
        if (ck(st, 33)) {
            ds = st[26];
            dl = st[27];
            hasdrop = 1;
            adv(p, n, st);
        }
        if (acc(p, n, st, 32)) {
            caps = 1;
        }
        if (acc(p, n, st, 36)) {
            isown = 1;
        }
        if (ck(st, 22)) {
            adv(p, n, st);
            if ((which == 1)) {
                pstruct(p, n, st, isown, hasdrop, ds, dl, ps);
            }
            if ((which != 1)) {
                skip_item(p, n, st);
            }
            continue;
        }
        if (ck(st, 24)) {
            adv(p, n, st);
            if ((which == 2)) {
                penum(p, n, st, ps);
            }
            if ((which != 2)) {
                skip_item(p, n, st);
            }
            continue;
        }
        if (ck(st, 8)) {
            if ((which == 3)) {
                adv(p, n, st);
                pextern(p, n, st, caps, ps);
            }
            if ((which != 3)) {
                skip_item(p, n, st);
            }
            continue;
        }
        if (ck(st, 10)) {
            if ((which == 4)) {
                adv(p, n, st);
                pfn(p, n, st, caps, ps);
            }
            if ((which != 4)) {
                skip_item(p, n, st);
            }
            continue;
        }
        if (ck(st, 27)) {
            adv(p, n, st);
            if ((which == 5)) {
                pimpl(p, n, st, ps);
            }
            if ((which != 5)) {
                skip_item(p, n, st);
            }
            continue;
        }
        perr(st);
        going = 0;
    }
}

nyx_i64 main(nyx_i64 __argc, nyx_u8** __argv) {
    __nyx_args_set(__argc, __argv);
    nyx_str path = ((nyx_str){"/tmp/n_parse_target.n", 21});
    if ((nyx_arg_count() > 1)) {
        path = nyx_arg(1);
    }
    nyx_i64 fd = sys_open((nyx_u8*)(((nyx_u8*)path.ptr)), 0, 0);
    if ((fd < 0)) {
        put(((nyx_str){"(no parse target - skipped)\n", 28}));
        return 0;
    }
    nyx_u8* buf = (nyx_u8*)(sys_sbrk(262144));
    nyx_i64 total = 0;
    nyx_i64 r = 1;
    while ((r > 0)) {
        r = sys_read(fd, (nyx_u8*)(((nyx_addr)(buf) + (nyx_addr)(total))), 16384);
        if ((r > 0)) {
            total = (total + r);
        }
    }
    sys_close(fd);
    if ((total < 1)) {
        return 0;
    }
    nyx_i64* st = (nyx_i64*)(sys_sbrk(512));
    nyx_i64* ps = (nyx_i64*)(sys_sbrk(1024));
    nyx_i64 pass = 1;
    while ((pass <= 5)) {
        st[0] = 0;
        st[1] = 1;
        st[2] = -(1);
        st[3] = 0;
        st[4] = 0;
        st[32] = 0;
        adv(buf, total, st);
        adv(buf, total, st);
        pass_items(buf, total, st, pass, ps);
        pass = (pass + 1);
    }
    put(((nyx_str){".\n", 2}));
    return 0;
}

/* nyxrt.c — Nyx C runtime implementation. Freestanding, no libc calls. */
#include "nyxrt.h"

/* crt0 publishes the process environment here (it references `environ` on every
 * launch). Cross-compiled N programs link nyxrt INSTEAD of libc, so the symbol
 * must live here too — even though nothing in the N runtime reads it yet.
 * In-OS builds (the `cc` builtin, milestone M3) always link /libc.o, which
 * already defines environ — defining it here too would be a duplicate symbol,
 * so the in-OS (tcc) build leaves it to libc. */
#ifndef __TINYC__
char** environ = 0;
#endif

nyx_str __nyx_fmt_begin(char* buf, nyx_u64 cap) {
    (void)cap;
    if (cap) buf[0] = '\0';
    return (nyx_str){ buf, 0 };
}

/* Append n bytes, always NUL-terminating, never overflowing cap. */
static void nyx_append(nyx_str* d, char* buf, nyx_u64 cap, const char* s, nyx_u64 n) {
    nyx_u64 i = 0;
    while (i < n && d->len + 1 < cap) buf[d->len++] = s[i++];
    if (cap) buf[d->len] = '\0';
    d->ptr = buf;
}

void __nyx_fmt_str(nyx_str* d, char* buf, nyx_u64 cap, nyx_str s) {
    nyx_append(d, buf, cap, s.ptr, s.len);
}

void __nyx_fmt_i64(nyx_str* d, char* buf, nyx_u64 cap, nyx_i64 v) {
    char tmp[24];
    int  ti = 0;
    int  neg = 0;
    nyx_u64 uv;
    if (v < 0) { neg = 1; uv = (nyx_u64)(-(v + 1)) + 1; }  /* handles INT64_MIN */
    else         uv = (nyx_u64)v;
    if (uv == 0) tmp[ti++] = '0';
    while (uv) { tmp[ti++] = (char)('0' + (int)(uv % 10)); uv /= 10; }
    if (neg) tmp[ti++] = '-';
    char out[24];
    int  oi = 0;
    while (ti) out[oi++] = tmp[--ti];   /* reverse */
    nyx_append(d, buf, cap, out, (nyx_u64)oi);
}

/* v0.21 "{expr:wN}" / "{expr:zN}" (optionally composed with x/X): format
 * the number, then right-align it in `width` columns. Zero padding puts
 * the sign FIRST ("-0042", the convention every C formatter follows);
 * space padding puts it with the digits ("  -42"). Hex still shows the
 * u64 bit pattern, so no sign appears in hex mode. A value wider than
 * the field is printed in full — width is a minimum, never a cut. */
void __nyx_fmt_num(nyx_str* d, char* buf, nyx_u64 cap, nyx_i64 v,
                   int hex, int upper, int width, int zero) {
    const char* dig = upper ? "0123456789ABCDEF" : "0123456789abcdef";
    char tmp[24];
    int  ti = 0;
    int  neg = 0;
    nyx_u64 uv;
    if (hex) {
        uv = (nyx_u64)v;
        if (uv == 0) tmp[ti++] = '0';
        while (uv) { tmp[ti++] = dig[uv & 15]; uv >>= 4; }
    } else {
        if (v < 0) { neg = 1; uv = (nyx_u64)(-(v + 1)) + 1; }  /* INT64_MIN-safe */
        else         uv = (nyx_u64)v;
        if (uv == 0) tmp[ti++] = '0';
        while (uv) { tmp[ti++] = (char)('0' + (int)(uv % 10)); uv /= 10; }
    }
    char out[160];
    int  oi = 0;
    int  pad = width - ti - neg;
    if (zero) {
        if (neg) out[oi++] = '-';
        while (pad > 0) { out[oi++] = '0'; pad--; }
    } else {
        while (pad > 0) { out[oi++] = ' '; pad--; }
        if (neg) out[oi++] = '-';
    }
    while (ti) out[oi++] = tmp[--ti];   /* reverse the digits */
    nyx_append(d, buf, cap, out, (nyx_u64)oi);
}

/* v0.20 "{expr:x}" / "{expr:X}": hex shows the raw bit pattern, so the
 * value arrives as u64 — a negative i64 prints as its two's-complement
 * image, the reading a systems programmer expects from hex. */
void __nyx_fmt_hex(nyx_str* d, char* buf, nyx_u64 cap, nyx_u64 v, int upper) {
    const char* dig = upper ? "0123456789ABCDEF" : "0123456789abcdef";
    char tmp[16];
    int  ti = 0;
    if (v == 0) tmp[ti++] = '0';
    while (v) { tmp[ti++] = dig[v & 15]; v >>= 4; }
    char out[16];
    int  oi = 0;
    while (ti) out[oi++] = tmp[--ti];   /* reverse */
    nyx_append(d, buf, cap, out, (nyx_u64)oi);
}
